// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgn35Aibll54Q44Ht9LeuRuuue4p5q0Zo',
    appId: '1:551854441061:web:ef7104ecd77520005efc8c',
    messagingSenderId: '551854441061',
    projectId: 'cpicpi',
    authDomain: 'cpicpi.firebaseapp.com',
    storageBucket: 'cpicpi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoG4gqtXw1zSEavY6DWBlEy7JagsxfApM',
    appId: '1:551854441061:android:efa014352b70be465efc8c',
    messagingSenderId: '551854441061',
    projectId: 'cpicpi',
    storageBucket: 'cpicpi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa8fcAo3_wps5Qp_EIni5eHn02T-blSkU',
    appId: '1:551854441061:ios:1f6a1b7756eff67d5efc8c',
    messagingSenderId: '551854441061',
    projectId: 'cpicpi',
    storageBucket: 'cpicpi.appspot.com',
    iosClientId: '551854441061-qv4ahovvlmaefi27mijj2bqcpg8caq8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpi3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa8fcAo3_wps5Qp_EIni5eHn02T-blSkU',
    appId: '1:551854441061:ios:1f6a1b7756eff67d5efc8c',
    messagingSenderId: '551854441061',
    projectId: 'cpicpi',
    storageBucket: 'cpicpi.appspot.com',
    iosClientId: '551854441061-qv4ahovvlmaefi27mijj2bqcpg8caq8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpi3',
  );
}
